drop table if exists book;
drop table if exists author;

create table book (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                      isbn VARCHAR(255),
                      publisher VARCHAR(255),
                      title VARCHAR(255),
                      author_id BIGINT,
                      PRIMARY KEY (id)
);

create table author (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        first_name VARCHAR(255),
                        last_name VARCHAR(255),
                        PRIMARY KEY (id)
);